### ISSUE TITLE
How can I get the file "TextPositionDetector.apply"

### ISSUE THREAD

**Issue by sgy-ecnu** [MX-Futhark/text-position-detector#1]
How can I get the file "TextPositionDetector.apply". In your source code doesn't exist such file

**Comment by MX-Futhark** [comment]
Hello @sgy-ecnu, `TextPositionDetector.apply` is a static method located in `src/textlocator/TextPositionDetector.java`.

Note that usage questions do not really have their place in github issues. I suggest you send me an email so that I can walk you through the steps if the information above doesn't help you.
